### ISSUE TITLE
Needs a LICENSE

### ISSUE THREAD

**Issue by annevk** [whatwg/participate.whatwg.org#114]
I guess we want the standard WHATWG CC license here due to it including SG text.

**Comment by domenic** [comment]
Well, but this is primarily a software project... hmm.

**Comment by foolip** [comment]
Would the license file in https://github.com/whatwg/sg/pull/115 (CC-BY + BSD) work for this repo?

**Comment by domenic** [comment]
See https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software and https://opensource.stackexchange.com/a/1718 for why CC-BY might not be appropriate for software. Maybe having BSD be an alternative makes it better; I dunno.

To be clear, if someone wants to send a PR and stand behind it, I am fine to merge it; this doesn't mater much to me. I'm just pointing out some potential friction.
