### ISSUE TITLE
Make it clearer that organization members have to make public that fact themselves

### ISSUE THREAD

**Issue by annevk** [whatwg/participate.whatwg.org#12]
That is, currently GitHub doesn't allow an organization to force its members to demonstrate membership. It's a choice of the members.

This might not be clear to the person signing the agreement and it might not be clear to the members of the organization either. We should probably have some guidance, including specific instructions, to help with this.

**Comment by domenic** [comment]
https://participate.whatwg.org/agreement says

> For the purposes of easily allowing contributions from persons associated to the Entity, the WHATWG requires Entities to identify an existing GitHub organization whose members are associated with the Entity. All public members of this GitHub organization will be able to contribute on behalf of the Entity.

but yes, we could try to make something more user-facing. Help welcome.

**Comment by domenic** [comment]
Oh, it's also on the user-facing troubleshooting page linked to from the PR: e.g. https://participate.whatwg.org/agreement-status?user=rmisev&repo=url says

> If you think you are associated with an entity that has signed up to participate, then ensure that you have publicly displayed your affiliation with that entity's GitHub organization. For more information on how to do this, see the GitHub help article, "Publicizing or hiding organization membership".

**Comment by annevk** [comment]
Ah okay. I guess that should be clear enough.

**Comment by domenic** [comment]
So if GitHub was willing to add features to help with this, it would be nice if there was some master switch on the organization level, so that joining an organization required publicizing your membership.

**Comment by othermaciej** [comment]
In the meantime maybe I will a repository with a README to the apple-whatwg org to point people to after they join. Still, I bet most will forget to do this. I had a hard time figuring out how to do it even after told I was supposed to.

**Comment by dbaron** [comment]
For a given organization it's easy to link people to the right URL, although they still have to scroll to find themselves.  For example, for mozilla-standards I can link people to https://github.com/orgs/mozilla-standards/people (which I do via https://wiki.mozilla.org/Standards/GitHub_IPR_Organization).

**Comment by michaelchampion** [comment]
Good ideas, I will do something like these things for our GitHub organization that tracks WHATWG participation.
