### ISSUE TITLE
Sometimes the deploy restart doesn't work

### ISSUE THREAD

**Issue by domenic** [whatwg/participate.whatwg.org#18]
I sometimes get "502 Bad Gateway", implying that nginx can't find the backing node server, after a Travis CI initiated deploy. Re-deploying, or SSHing in to restart, fixes it.

I'm not sure how to debug this or what could be going wrong here, but I want to file a tracking issue at least. Maybe I'm not using pm2 correctly :-/.

**Comment by foolip** [comment]
Anything in the logs that proves deploy made it past the restart bit of the script? If not, maybe add logging after to see if something funny happens when it doesn't work?

**Comment by domenic** [comment]
Yeah the Travis CI logs imply a successful restart, I am pretty sure. Although I guess re-starting a deploy wipes out the logs so I can't link to any evidence. I'll keep an eye out next time.

**Comment by domenic** [comment]
I see some stuff in the logs on the server that implies some problems starting up. But, no timestamps, so it is hard to confirm. Adding better logging would probably be a good idea. And, if the failures are at the same time, figuring out why they aren't getting echoed back to CI.

My current hypothesis is that auto-deploy always fails and that it's due to some difference in environment when SSHing via Travis vs. SSHing manually. Maybe it's as simple as being in the wrong folder or something.

Will investigate more some other time.

**Comment by domenic** [comment]
Confirmed fixed by https://github.com/whatwg/misc-server/pull/88; when that's merged we can close this.
