### ISSUE TITLE
Update GitHub link to not conditionally 404

### ISSUE THREAD

**Issue by GloverDonovan** [whatwg/participate.whatwg.org#19]
The [current link](https://github.com/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+user%3Awhatwg) for the "good first issue"  tag throws a 404 error when the user is not logged in with a GitHub account.

I propose that [this link](https://github.com/search?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22good+first+issue%22+user%3Awhatwg&type=Issues) be used instead since observers can view the page without having to log in (and aren't greeted with a 404 error implying that the link is broken).

Advantages:

- Doesn't 404 when the user isn't logged in with a GitHub account
- Larger font size given to the number of open issues
- Excerpts for each issue make it easier to understand the topic at hand
- IMO easier to see which repository each issue is in (the current link hides repository names in the issue title)

Disadvantages:

- Less issues per page (this probably doesn't matter since newcomers will want to choose one issue and work on that)
- Tags aren't visible (could be considered both an advantage and disadvantage)

Wouldn't mind making a pull request to fix this.

**Comment by domenic** [comment]
I wasn't aware this was possible. Pull request welcome!!
