### ISSUE TITLE
GitHub usernames are case-insensitive, I think?

### ISSUE THREAD

**Issue by domenic** [whatwg/participate.whatwg.org#34]
https://github.com/whatwg/participant-data/commit/815fbc62892578a918c1366ed6ce15124add5f63 added a user under the name "johanna-hub", but the official spelling of their username is "Johanna-hub", with an uppercase letter. So the PR https://github.com/whatwg/html/pull/4068 was initially marked as not-OK.

I manually fixed participant-data as a one-off in this case. But, we should consider a better solution for the future. Either case-insensitive comparison, or canonicalization, or...

Related: #8.

**Comment by annevk** [comment]
@DOMENIC test.

**Comment by annevk** [comment]
Hmm, so if I type `@DOMENIC` it stores that, but it shows a canonicalized version. Not sure what to make of that. Case-insensitive I guess.
