### ISSUE TITLE
Add some text on the home page for "hey I have an idea"

### ISSUE THREAD

**Issue by gsnedders** [whatwg/participate.whatwg.org#37]
At the moment, you can eventually find something in the way of an answer by going from WHATWG home -> Participate -> Working Mode (read a lot till you find the relevant heading), but that really just says that it will be incubated outside of any WHATWG standard, so… where do I send a proposal? Who to? Where?

See the thread from https://twitter.com/troglotit/status/1109568782215852033.

**Comment by domenic** [comment]
I think we should do this prominently on the homepage, especially because whatwg.org links to participate.whatwg.org with the "Get started with contributing to the WHATWG" text. Let me try to draft something.
