### ISSUE TITLE
"An internal error was encountered processing your request."

### ISSUE THREAD

**Issue by adroitwhiz** [whatwg/participate.whatwg.org#92]
Filling out the form always seems to give me a 500 error:
![image](https://user-images.githubusercontent.com/25993062/77019889-4d1ce800-6958-11ea-804a-f22d15f825b7.png)

I've tried a few different times but this error seems to persist. Are you able to reproduce this error?

**Comment by domenic** [comment]
Thank you for bring this to our attention! I put up a fix in #93, and will merge it momentarily.

This is yet more fallout from me not sufficiently vetting the Octokit major version upgrade; see also https://github.com/whatwg/participate.whatwg.org/commit/33f3eb6ef3a4c0e43a9bc7cec5a52dd14ed15523 and https://github.com/whatwg/participate.whatwg.org/commit/6fa872808ba2b9eaa919a3131cd8a1d3d7c30425. I think the lesson has been thoroughly learned at this point that any Octokit upgrades will require thorough manual testing before merging. (Or better, significant investment in writing automated integration tests, although that will be a good amount of work.)
